## Merging csv

In [30]:
import os
import pandas as pd

def merge_csv_files(folder_path, output_file):
    """
    Merge all CSV files in a folder into one CSV file.
    
    Parameters:
    - folder_path: Path to the folder containing CSV files
    - output_file: Full path to the output merged CSV file
    """
    # List all .csv files in the folder
    csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
    
    # Read and concatenate all CSVs
    df_list = []
    for file in csv_files:
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)
        df_list.append(df)
    
    merged_df = pd.concat(df_list, ignore_index=True)
    
    # Save to output file
    merged_df.to_csv(output_file, index=False)
    print(f"Merged {len(csv_files)} CSV files into '{output_file}'")

# Example usage:
folder = r"D:\Aamir Gulzar\KSA_project2\paip_data\patches_metadata"  # Replace with your folder
output = r"D:\Aamir Gulzar\KSA_project2\paip_data\merged_output.csv"
merge_csv_files(folder, output)

Merged 73 CSV files into 'D:\Aamir Gulzar\KSA_project2\paip_data\merged_output.csv'

## Running model on csv

In [58]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Shuffle the dataframe
dftest = pd.read_csv(r"D:\Aamir Gulzar\KSA_project2\paip_data\merged_output.csv")
feature_cols= ['avg_B', 'std_G', 'std_B']

X = dftest[feature_cols].values

In [59]:
dftest

,patch_location,patch_name,patch_number,patch_x,patch_y,avg_R,avg_G,avg_B,std_R,std_G,std_B
0,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x8192_y44776_patch00000.png,0,8192,44776,183.99,184.26,185.03,83.80,83.56,82.61
1,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x8704_y44776_patch00001.png,1,8704,44776,183.99,184.41,185.07,83.48,83.19,82.27
2,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x9216_y44776_patch00002.png,2,9216,44776,183.74,183.99,184.75,83.61,83.38,82.45
3,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x9728_y44776_patch00003.png,3,9728,44776,182.78,183.20,183.84,83.88,83.61,82.71
4,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x10240_y44776_patch00004...,4,10240,44776,183.15,183.47,184.25,83.45,83.23,82.26
...,...,...,...,...,...,...,...,...,...,...,...
272409,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48272_y17136_patch...,4819,48272,17136,213.82,201.38,213.42,35.76,42.40,32.67
272410,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48272_y19184_patch...,4820,48272,19184,219.72,208.82,221.75,34.59,43.14,28.89
272411,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48272_y19696_patch...,4821,48272,19696,226.36,219.51,228.13,28.34,35.25,24.08
272412,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48784_y16624_patch...,4822,48784,16624,222.29,210.55,219.74,33.44,39.39,32.08
272413,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48784_y17136_patch...,4823,48784,17136,225.35,221.17,225.79,43.91,46.35,43.01

In [60]:
import joblib
svm_model = joblib.load('svm_model_rbf.pkl')
scaler = joblib.load('scaler_rbf.pkl')

In [61]:
X_scaled = scaler.transform(X)
y_pred = svm_model.predict(X_scaled)

In [62]:
dftest["label"]=y_pred

In [63]:
dftest

,patch_location,patch_name,patch_number,patch_x,patch_y,avg_R,avg_G,avg_B,std_R,std_G,std_B,label
0,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x8192_y44776_patch00000.png,0,8192,44776,183.99,184.26,185.03,83.80,83.56,82.61,1
1,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x8704_y44776_patch00001.png,1,8704,44776,183.99,184.41,185.07,83.48,83.19,82.27,1
2,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x9216_y44776_patch00002.png,2,9216,44776,183.74,183.99,184.75,83.61,83.38,82.45,1
3,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x9728_y44776_patch00003.png,3,9728,44776,182.78,183.20,183.84,83.88,83.61,82.71,1
4,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,training_data_01_MSIH_x10240_y44776_patch00004...,4,10240,44776,183.15,183.47,184.25,83.45,83.23,82.26,1
...,...,...,...,...,...,...,...,...,...,...,...,...
272409,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48272_y17136_patch...,4819,48272,17136,213.82,201.38,213.42,35.76,42.40,32.67,0
272410,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48272_y19184_patch...,4820,48272,19184,219.72,208.82,221.75,34.59,43.14,28.89,0
272411,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48272_y19696_patch...,4821,48272,19696,226.36,219.51,228.13,28.34,35.25,24.08,0
272412,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48784_y16624_patch...,4822,48784,16624,222.29,210.55,219.74,33.44,39.39,32.08,0
272413,D:\Aamir Gulzar\KSA_project2\paip_data\patch_d...,validation_data_31_nonMSIH_x48784_y17136_patch...,4823,48784,17136,225.35,221.17,225.79,43.91,46.35,43.01,1

In [65]:
len(dftest[dftest['label']==1])

1092

In [66]:
final_df= dftest[dftest["label"]==0]

In [67]:
final_df.to_csv(r"D:\Aamir Gulzar\KSA_project2\paip_data\final_merged_without_white.csv", index=False)